server:
  port: 8502

spring:
  application:
    name: tickets-service
  rabbitmq:
    username: haydikodlayalim
    password: haydikodlayalim
    cloud:
      stream:
        bindings:
          output:
            destination: msqueue
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  datasource:
    url: jdbc:mysql://localhost:3306/microservicesapp
    username: root
    password: microservices-app
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
